### ISSUE TITLE
does nothing but load the landing

### ISSUE THREAD

**Issue by R-Sqwared** [A2TC-YT/afk-class-item-double-chest#6]
i've let this script run for 10 minutes and all it does is change characters, load the landing, stand there, then give the message "didn't detect spawn in :(" and repeats the process

**Comment by Asha-00** [comment]
> i've let this script run for 10 minutes and all it does is change characters, load the landing, stand there, then give the message "didn't detect spawn in :(" and repeats the process

Not Detecting Load in.
This is caused by the script not detecting something based on colors/Brightness.
It detects load in by looking for the purple in your heavy ammo icon in a specific place.

Check your brightness settings are at max (7) in game
Screen bounds in destiny are maxed and SAVED by pushing enter.

Make sure hud is full opacity.
Turn off any overlays you use.

Disable any bluelight filters
Check windows HDR settings and Nvidia HDR

Check that Night-light and Colorblind settings are OFF in windows display settings

**Comment by R-Sqwared** [comment]
> > i've let this script run for 10 minutes and all it does is change characters, load the landing, stand there, then give the message "didn't detect spawn in :(" and repeats the process
> 
> Not Detecting Load in. This is caused by the script not detecting something based on colors/Brightness. It detects load in by looking for the purple in your heavy ammo icon in a specific place.
> 
> Check your brightness settings are at max (7) in game Screen bounds in destiny are maxed and SAVED by pushing enter.
> 
> Make sure hud is full opacity. Turn off any overlays you use.
> 
> Disable any bluelight filters Check windows HDR settings and Nvidia HDR
> 
> Check that Night-light and Colorblind settings are OFF in windows display settings

i closed GeForce's overlay and it works fine

**Comment by EnforcerRyan** [comment]
To add to this, might want to tell people not to use void swords. Switched from guillotine to slammer and everything works perfect now
